export const metadata = {
	title: 'One to Grow On',
	subtitle: 'Understanding how food production impacts ourselves and our world',
	description:
		'One to Grow On is a podcast where we dig into questions about agriculture and try to understand how food production impacts us and our world.',
	author: '@onetogrowonpod, Hallie Casey, Chris Casey',
	url: 'https://www.onetogrowonpod.com',
	siteUrl: 'https://www.onetogrowonpod.com',
	twitterUsername: '@onetogrowonpod',
	keywords: [
		'agriculture',
		'science',
		'podcast',
		'green new deal',
		'aoc',
		'biodiesel',
		'farming',
		'food',
		'superfoods',
		'agriculture podcast',
		'farming podcast',
		'food podcast',
		'plant science',
		'gardening',
		'gardening podcast',
		'bugs',
		'pollenators',
	],
};
